services:
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: c6h5bwInqtKJKmiuPcBQ0A
            MYSQL_DATABASE: labbd
            MYSQL_USER: grupo3
            MYSQL_PASSWORD: grupo3
        command: [ '--local-infile=1', '--secure-file-priv=/var/lib/mysql-files/' ]
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./mysql-files:/var/lib/mysql-files

volumes:
    db_data:
